name: Example workflow for S3 Deploy
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-2
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install
          
        - name: Build Website
          run: npm run build
          
        - name: Set AWS credentials
          uses: aws-action/configure-aws-credentials@v1
          
        - name: Copy to S3
          run: aws s3 sync ./build/. s3://tic-tac-website

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            

