name: Example workflow for S3 Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - name: Install dependencies
          run: npm install
          
        - name: Build Website
          run: npm run build
          
        - name: set AWS credentials
        - name: aws-actions/configure-aws-credentials@v1
          with:
               aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: us-east-2
        - name: Deploy to S3
          run: npm run deploy
        
         
             


    
  
            

