name: Tic-tac workflow for S3 Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - name: Install dependencies
          run: npm install
          
        - name: Build Website
          run: npm run build
          
        - name: set AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: us-east-2
        - name: Copy to S3
          run: aws s3 sync ./build/. s3://tic-tac-website
        
         
             


    
  
            

